name: Deploy WhatsApp Bot

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository URL'
        required: true
        type: string
      token:
        description: 'GitHub Token'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Deploy bot
        run: npm run deploy # Replace this with your actual deploy script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
